# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8888:80
        volumes:
            - ./src:/var/www/html
            - ./src/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql
        ports:
            - 33069:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './mysql:/var/lib/mysql'
        networks:
            - laravel
    php:
        build:
            context: . 
            dockerfile: Dockerfile
        container_name: php 
        volumes: 
            - ./src:/var/www/html
        ports:
            - 9000:80
        networks:
            - laravel
networks:
    laravel:

