# For more information: https://laravel.com/docs/sail
version: '3.7'
services:
    app:
        image: nginx:stable-alpine
        container_name: app
        ports:
            - 8888:80
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    mysql:
        image: mariadb:10
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './mysql:/var/lib/mysql'
        networks:
            - laravel
    php:
        build:
            context: . 
            dockerfile: Dockerfile
        container_name: php 
        volumes: 
            - ./:/var/www/html
        ports:
            - 9000:80
        networks:
            - laravel
networks:
    laravel:

